// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LotteryContract$Type } from "./LotteryContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LotteryContract"]: LotteryContract$Type;
    ["contracts/Lottery.sol:LotteryContract"]: LotteryContract$Type;
  }

  interface ContractTypesMap {
    ["LotteryContract"]: GetContractReturnType<LotteryContract$Type["abi"]>;
    ["contracts/Lottery.sol:LotteryContract"]: GetContractReturnType<LotteryContract$Type["abi"]>;
  }
}
