// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Tokenizer$Type } from "./Tokenizer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Tokenizer"]: Tokenizer$Type;
    ["contracts/Tokenizer.sol:Tokenizer"]: Tokenizer$Type;
  }

  interface ContractTypesMap {
    ["Tokenizer"]: GetContractReturnType<Tokenizer$Type["abi"]>;
    ["contracts/Tokenizer.sol:Tokenizer"]: GetContractReturnType<Tokenizer$Type["abi"]>;
  }
}
