// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DomaDomainAuction$Type } from "./DomaDomainAuction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DomaDomainAuction"]: DomaDomainAuction$Type;
    ["contracts/EnglishAuction.sol:DomaDomainAuction"]: DomaDomainAuction$Type;
  }

  interface ContractTypesMap {
    ["DomaDomainAuction"]: GetContractReturnType<DomaDomainAuction$Type["abi"]>;
    ["contracts/EnglishAuction.sol:DomaDomainAuction"]: GetContractReturnType<DomaDomainAuction$Type["abi"]>;
  }
}
