// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDomaRecord$Type } from "./IDomaRecord";
import { IERC721Minimal$Type } from "./IERC721Minimal";
import { IProxyDomaRecord$Type } from "./IProxyDomaRecord";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDomaRecord"]: IDomaRecord$Type;
    ["IERC721Minimal"]: IERC721Minimal$Type;
    ["IProxyDomaRecord"]: IProxyDomaRecord$Type;
    ["contracts/interfaces/IDoma.sol:IDomaRecord"]: IDomaRecord$Type;
    ["contracts/interfaces/IDoma.sol:IERC721Minimal"]: IERC721Minimal$Type;
    ["contracts/interfaces/IDoma.sol:IProxyDomaRecord"]: IProxyDomaRecord$Type;
  }

  interface ContractTypesMap {
    ["IDomaRecord"]: GetContractReturnType<IDomaRecord$Type["abi"]>;
    ["IERC721Minimal"]: GetContractReturnType<IERC721Minimal$Type["abi"]>;
    ["IProxyDomaRecord"]: GetContractReturnType<IProxyDomaRecord$Type["abi"]>;
    ["contracts/interfaces/IDoma.sol:IDomaRecord"]: GetContractReturnType<IDomaRecord$Type["abi"]>;
    ["contracts/interfaces/IDoma.sol:IERC721Minimal"]: GetContractReturnType<IERC721Minimal$Type["abi"]>;
    ["contracts/interfaces/IDoma.sol:IProxyDomaRecord"]: GetContractReturnType<IProxyDomaRecord$Type["abi"]>;
  }
}
