// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IProxyDomaRecord$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IProxyDomaRecord",
  "sourceName": "contracts/interfaces/IDoma.sol",
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "components": [
                {
                  "internalType": "string",
                  "name": "sld",
                  "type": "string"
                },
                {
                  "internalType": "string",
                  "name": "tld",
                  "type": "string"
                }
              ],
              "internalType": "struct IDomaRecord.NameInfo[]",
              "name": "names",
              "type": "tuple[]"
            },
            {
              "internalType": "uint256",
              "name": "nonce",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "expiresAt",
              "type": "uint256"
            },
            {
              "internalType": "address",
              "name": "ownerAddress",
              "type": "address"
            }
          ],
          "internalType": "struct IProxyDomaRecord.TokenizationVoucher",
          "name": "voucher",
          "type": "tuple"
        },
        {
          "internalType": "bytes",
          "name": "signature",
          "type": "bytes"
        }
      ],
      "name": "requestTokenization",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IProxyDomaRecord",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IProxyDomaRecord$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/IDoma.sol:IProxyDomaRecord",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IProxyDomaRecord$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IProxyDomaRecord",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IProxyDomaRecord$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/IDoma.sol:IProxyDomaRecord",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IProxyDomaRecord$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IProxyDomaRecord",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IProxyDomaRecord$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/IDoma.sol:IProxyDomaRecord",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IProxyDomaRecord$Type["abi"]>>;
}
